"""account and expense table

Revision ID: 2588269bdd1a
Revises: 69db2f3763ec
Create Date: 2024-01-31 20:53:29.703777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2588269bdd1a'
down_revision = '69db2f3763ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_user_id'), ['user_id'], unique=False)

    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_spent', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=80), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_name'))
        batch_op.drop_index(batch_op.f('ix_expense_category'))
        batch_op.drop_index(batch_op.f('ix_expense_account_id'))

    op.drop_table('expense')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_group'))

    op.drop_table('account')
    # ### end Alembic commands ###
