"""add provider field to subscriptions

Revision ID: aa223e189857
Revises: b123b8397468
Create Date: 2024-03-14 23:06:29.878924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa223e189857'
down_revision = 'b123b8397468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_subscription_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_provider'))
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
