"""add subscriptions table

Revision ID: b123b8397468
Revises: e5d356989b5a
Create Date: 2024-03-13 23:04:56.721961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b123b8397468'
down_revision = 'e5d356989b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_billing'), ['billing'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_status'), ['status'], unique=False)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_year_month_user', ['year', 'month', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint('unique_year_month_user', type_='unique')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_status'))
        batch_op.drop_index(batch_op.f('ix_subscription_category'))
        batch_op.drop_index(batch_op.f('ix_subscription_billing'))
        batch_op.drop_index(batch_op.f('ix_subscription_account_id'))

    op.drop_table('subscription')
    # ### end Alembic commands ###
